In [2]:
from __future__ import print_function
import torch

In [3]:
#unintialized matrix
x = torch.empty(5, 3)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [5]:
x = torch.rand(5, 3)
print(x)

tensor([[0.6008, 0.8540, 0.3011],
        [0.2878, 0.7795, 0.9862],
        [0.0877, 0.8520, 0.0589],
        [0.5589, 0.8624, 0.4843],
        [0.3758, 0.5014, 0.8483]])


In [6]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [7]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [8]:
x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [9]:
x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)

tensor([[-0.5032, -0.4872,  0.5766],
        [ 0.2371, -1.3205, -0.3246],
        [-0.2321, -0.6170,  0.6928],
        [ 1.3977,  1.7260,  1.0882],
        [ 0.2054,  0.8911,  1.2434]])


In [10]:
print(x.size())

torch.Size([5, 3])


In [11]:
y = torch.rand(5, 3)
print(x + y)

tensor([[-0.3847,  0.4005,  0.6669],
        [ 1.1965, -0.6100, -0.1110],
        [ 0.7525, -0.0729,  1.0999],
        [ 1.7388,  1.9380,  1.2708],
        [ 0.3656,  0.9091,  2.1599]])


In [12]:
print(torch.add(x, y))

tensor([[-0.3847,  0.4005,  0.6669],
        [ 1.1965, -0.6100, -0.1110],
        [ 0.7525, -0.0729,  1.0999],
        [ 1.7388,  1.9380,  1.2708],
        [ 0.3656,  0.9091,  2.1599]])


In [13]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)    #out=output tensor (deifned )
print(result)

tensor([[-0.3847,  0.4005,  0.6669],
        [ 1.1965, -0.6100, -0.1110],
        [ 0.7525, -0.0729,  1.0999],
        [ 1.7388,  1.9380,  1.2708],
        [ 0.3656,  0.9091,  2.1599]])


In [14]:
# adds x to y
y.add_(x)
print(y)

tensor([[-0.3847,  0.4005,  0.6669],
        [ 1.1965, -0.6100, -0.1110],
        [ 0.7525, -0.0729,  1.0999],
        [ 1.7388,  1.9380,  1.2708],
        [ 0.3656,  0.9091,  2.1599]])


In [15]:
print(x[:, 1])

tensor([-0.4872, -1.3205, -0.6170,  1.7260,  0.8911])


In [17]:
x = torch.randn(4, 4)
y = x.view(16)
y

tensor([ 0.5291,  0.5247, -0.6912, -0.4170,  0.5934,  0.9439,  0.4130,  0.0804,
        -0.2692, -0.6458, -0.8492, -0.4527,  0.6579,  0.1905,  0.5652, -0.3568])

In [18]:
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [19]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([-0.6981])
-0.698086678981781


In [20]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [21]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [22]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [23]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [4]:
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!

C:\Users\5001\anaconda3\envs\dl_gpu\lib\site-packages\torch\cuda\__init__.py:125: UserWarning: 
GeForce GT 710 with CUDA capability sm_35 is not compatible with the current PyTorch installation.
The current PyTorch install supports CUDA capabilities sm_37 sm_50 sm_60 sm_61 sm_70 sm_75 compute_37.
If you want to use the GeForce GT 710 GPU with PyTorch, please check the instructions at https://pytorch.org/get-started/locally/

  warnings.warn(incompatible_device_warn.format(device_name, capability, " ".join(arch_list), device_name))


RuntimeError: CUDA error: no kernel image is available for execution on the device

In [7]:
a=torch.FloatTensor([1.0,2.0,3.0]).cuda()
a.device

device(type='cuda', index=0)

In [30]:
a.device

device(type='cpu')