In [1]:
import torch
import torch.utils.data as Data

torch.manual_seed(6)

In [2]:
x = torch.linspace(1,10,10)
y = torch.linspace(10,1,10)
torch.cat((x.view(len(x),-1),y.view(len(y),-1)),1)

tensor([[ 1., 10.],
        [ 2.,  9.],
        [ 3.,  8.],
        [ 4.,  7.],
        [ 5.,  6.],
        [ 6.,  5.],
        [ 7.,  4.],
        [ 8.,  3.],
        [ 9.,  2.],
        [10.,  1.]])

In [9]:
dataset = Data.TensorDataset(x, y)

In [10]:
BATCH_SIZE =  5

loader = Data.DataLoader(
    dataset=dataset,
    batch_size=BATCH_SIZE,
    shuffle=True,
    num_workers=1,
)

In [18]:
loader.batch_size
loader.num_workers

1

In [20]:
for step, (batch_x, batch_y) in enumerate(loader):
    print((batch_x, batch_y))

(tensor([5., 8., 6., 2., 9.]), tensor([6., 3., 5., 9., 2.]))
(tensor([ 3., 10.,  7.,  4.,  1.]), tensor([ 8.,  1.,  4.,  7., 10.]))


In [11]:
for epoch in range(3):
    for step, (batch_x, batch_y) in enumerate(loader):
        print('Epoch : ',epoch,'| Step', step, '| batch x :', batch_x.numpy(), "| bactch y : ",batch_y.numpy())

Epoch :  0 | Step 0 | batch x : [ 4.  1.  5.  2. 10.] | bactch y :  [ 7. 10.  6.  9.  1.]
Epoch :  0 | Step 1 | batch x : [7. 6. 8. 3. 9.] | bactch y :  [4. 5. 3. 8. 2.]
Epoch :  1 | Step 0 | batch x : [ 6.  9.  5.  3. 10.] | bactch y :  [5. 2. 6. 8. 1.]
Epoch :  1 | Step 1 | batch x : [2. 1. 8. 4. 7.] | bactch y :  [ 9. 10.  3.  7.  4.]
Epoch :  2 | Step 0 | batch x : [3. 6. 2. 1. 7.] | bactch y :  [ 8.  5.  9. 10.  4.]
Epoch :  2 | Step 1 | batch x : [ 8.  4.  9. 10.  5.] | bactch y :  [3. 7. 2. 1. 6.]


In [21]:
BATCH_SIZE = 8

loader = Data.DataLoader(
    dataset=dataset,      # torch TensorDataset format
    batch_size=BATCH_SIZE,      # mini batch size
    shuffle=True,               # random shuffle for training
    num_workers=1,              # subprocesses for loading data
)

for epoch in range(3):   # train entire dataset 3 times
    for step, (batch_x, batch_y) in enumerate(loader):  # for each training step
        
        # train your data...
        
        print('Epoch: ', epoch, '| Step: ', step, '| batch x: ',
              batch_x.numpy(), '| batch y: ', batch_y.numpy())

Epoch:  0 | Step:  0 | batch x:  [5. 3. 2. 6. 7. 1. 9. 4.] | batch y:  [ 6.  8.  9.  5.  4. 10.  2.  7.]
Epoch:  0 | Step:  1 | batch x:  [ 8. 10.] | batch y:  [3. 1.]
Epoch:  1 | Step:  0 | batch x:  [ 6.  9.  5. 10.  2.  8.  4.  3.] | batch y:  [5. 2. 6. 1. 9. 3. 7. 8.]
Epoch:  1 | Step:  1 | batch x:  [1. 7.] | batch y:  [10.  4.]
Epoch:  2 | Step:  0 | batch x:  [10.  3.  7.  4.  5.  2.  6.  8.] | batch y:  [1. 8. 4. 7. 6. 9. 5. 3.]
Epoch:  2 | Step:  1 | batch x:  [9. 1.] | batch y:  [ 2. 10.]


In [22]:
import torchvision
import torchvision.datasets as dsets
import torchvision.transforms as transforms

img_dir = "./images"
img_data = dsets.ImageFolder(img_dir, transforms.Compose([
            transforms.RandomSizedCrop(224),
            transforms.RandomHorizontalFlip(),
            transforms.ToTensor(),
            ]))

print(img_data.classes)
print(img_data.class_to_idx)
print(img_data.imgs)

C:\Users\5001\anaconda3\lib\site-packages\torchvision\transforms\transforms.py:751: UserWarning: The use of the transforms.RandomSizedCrop transform is deprecated, please use transforms.RandomResizedCrop instead.
  warnings.warn("The use of the transforms.RandomSizedCrop transform is deprecated, " +


FileNotFoundError: [WinError 3] The system cannot find the path specified: './images'

In [23]:
loader = Data.DataLoader(img_data, batch_size=3,
                            shuffle=True, num_workers=1)

for img,label in loader:
    print(img.size())
    print(label)

NameError: name 'img_data' is not defined

In [24]:

# MNIST Dataset 
train_dataset = dsets.MNIST(root='./data', 
                            train=True, 
                            transform=transforms.ToTensor(),  
                            download=True)

image, label = train_dataset[0]
print (image.size())
print (label)

Extracting ./data\MNIST\raw\train-images-idx3-ubyte.gz to ./data\MNIST\raw


Extracting ./data\MNIST\raw\train-labels-idx1-ubyte.gz to ./data\MNIST\raw


Extracting ./data\MNIST\raw\t10k-images-idx3-ubyte.gz to ./data\MNIST\raw


URLError: <urlopen error [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond>

In [25]:
train_loader = torch.utils.data.DataLoader(dataset=train_dataset,
                                          batch_size=100,
                                          shuffle=True,
                                          num_workers=2)

data_iter = iter(train_loader)

images, labels = data_iter.next()

for images, labels in train_loader:
    pass

images.size()

NameError: name 'train_dataset' is not defined